export const DIR_COUNTRIES = {
  EG: '🇪🇬 Egypt',
  GR: '🇬🇷 Greece',
  US: '🇺🇸 United States',
  AE: '🇦🇪 United Arab Emirates',
  AU: '🇦🇺 Australia',
  FR: '🇫🇷 France',
  GB: '🇬🇧 United Kingdom',
  MM: '🇲🇲 Myanmar',
  CA: '🇨🇦 Canada',
  CY: '🇨🇾 Cyprus',
  RU: '🇷🇺 Russia',
  CN: '🇨🇳 China',
  JP: '🇯🇵 Japan',
  TH: '🇹🇭 Thailand',
  IM: '🇮🇲 Isle of Man',
  NO: '🇳🇴 Norway',
  IR: '🇮🇷 Iran',
  SP: '🇪🇸 Spain',
  ES: '🇪🇸 Spain',
  SO: '🇸🇴 Somalia',
  TR: '🇹🇷 Turkey',
  DE: '🇩🇪 Germany',
  IT: '🇮🇹 Italy',
  BR: '🇧🇷 Brazil',
  MX: '🇲🇽 Mexico',
  AR: '🇦🇷 Argentina',
  CL: '🇨🇱 Chile',
  PE: '🇵🇪 Peru',
  CO: '🇨🇴 Colombia',
  VE: '🇻🇪 Venezuela',
  NL: '🇳🇱 Netherlands',
  BE: '🇧🇪 Belgium',
  CH: '🇨🇭 Switzerland',
  SE: '🇸🇪 Sweden',
  DK: '🇩🇰 Denmark',
  FI: '🇫🇮 Finland',
  PL: '🇵🇱 Poland',
  PT: '🇵🇹 Portugal',
  AT: '🇦🇹 Austria',
  IE: '🇮🇪 Ireland',
  NZ: '🇳🇿 New Zealand',
  ZA: '🇿🇦 South Africa',
  NG: '🇳🇬 Nigeria',
  KE: '🇰🇪 Kenya',
  IN: '🇮🇳 India',
  PK: '🇵🇰 Pakistan',
  BD: '🇧🇩 Bangladesh',
  ID: '🇮🇩 Indonesia',
  PH: '🇵🇭 Philippines',
  VN: '🇻🇳 Vietnam',
  KR: '🇰🇷 South Korea',
  IL: '🇮🇱 Israel',
  SA: '🇸🇦 Saudi Arabia',
  QA: '🇶🇦 Qatar',
  KW: '🇰🇼 Kuwait',
  OM: '🇴🇲 Oman',
  DEFAULT: 'No Definido',
};
